version: "3.9"

services:
  assistant:
    build: .
    image: assistant:local
    devices:
      - "/dev/snd:/dev/snd"
    volumes:
      - ./.models/vosk:/models/vosk
    environment:
      - RABBIT_URL=amqp://user:password@rabbitmq:5672/
      - SOURCE_NAME=assistant
      - WAKE_WORD=picovoice
      - VOSK_MODEL_PATH=/models/vosk
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # основной AMQP порт
      - "15672:15672" # веб-менеджер
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - ./.rabbitmq:/var/lib/rabbitmq
